### PR TITLE
Update settings.gradle

### PR DESCRIPTION
**Pull request by cesarferreira**
the demo module was "app" instead of "demo"

### CODE REVIEW

**Comment by fenjuly** [comment]
thanks

**Comment by cesarferreira** [comment]
Cool, [dryrun](https://github.com/cesarferreira/dryrun) works now ;)

> dryrun https://github.com/fenjuly/ToggleExpandLayout

**Comment by fenjuly** [comment]
Ii have already starred dryrun, it's very nice:)

César Ferreira notifications@github.com于2015年8月31日周一 下午9:25写道：

**Comment by cesarferreira** [comment]
Thanks a lot! :)

**Pull request merged**
